image: unoplatform/wasm-build:3.0

ports:
  - port: 8000
    onOpen: open-preview

tasks:
  # This task is run as part of the pre-build, but also during workspace init.
  # Forces the nuget restore path to be part of the restored workspace content,
  # so any subsequent build in the workspace will be faster (no nuget restore).
  - before: echo "export NUGET_PACKAGES=/workspace/.nuget" >> ~/.profile
    command: export NUGET_PACKAGES=/workspace/.nuget

  # This task is run during pre-build and it's log and built results are
  # restored as part of the workspace initialization.
  - prebuild: build/gitpod/build-all.sh
    command: export NUGET_PACKAGES=/workspace/.nuget

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
