jobs:
- job: Windows

  pool:
    vmImage: 'windows-2019'
    
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget

  steps:
  - checkout: self
    clean: true

  - task: UseDotNet@2
    displayName: 'Install .NET 5 SDK'
    inputs:
      packageType: sdk
      version: '5.0.400'

  - task: UseDotNet@2
    displayName: 'Install .NET 3.1.403'
    inputs:
      packageType: sdk
      version: 3.1.403

  - template: build/ci/gitversion.yml
  - template: build/ci/dotnet-install.yml

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.9.1
      checkLatest: false

  - bash: |
      npm install -g conventional-changelog-cli@2.2.2
      conventional-changelog -p angular -u -r 1 -o "build/CHANGELOG.md"
      sed -r -i 's/\[(.*?)\]\((.*?)\)/\2/g' build/CHANGELOG.md
    displayName: 'Generate CHANGELOG.MD'

  - powershell: |
        $ErrorActionPreference = 'SilentlyContinue'
        cd $(build.sourcesdirectory)/src/WasmAot.UITests
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.StaticLinking.Aot.UITests
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.Node.Sample.Runner
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.Threading.UITests
        npm install

    displayName: UI Tests npm dependencies

  - script: |
      cd $(build.sourcesdirectory)\src\Uno.Wasm.Bootstrap
      dotnet msbuild /r /p:Configuration=Release /p:InformationalVersion=$(GITVERSION.INFORMATIONALVERSION) /p:PackageReleaseNotesFile=$(Build.SourcesDirectory)/build/CHANGELOG.md /p:PackageVersion=$(GITVERSION.FullSemVer) /p:PackageOutputPath=$(build.sourcesdirectory)\build\nuget /bl:$(build.artifactstagingdirectory)/win-bootstrap.binlog
      cd $(build.sourcesdirectory)\src\Uno.Wasm.Bootstrap.DevServer
      dotnet msbuild /r /p:Configuration=Release /p:InformationalVersion=$(GITVERSION.INFORMATIONALVERSION) /p:PackageReleaseNotesFile=$(Build.SourcesDirectory)/build/CHANGELOG.md /p:PackageVersion=$(GITVERSION.FullSemVer) /p:PackageOutputPath=$(build.sourcesdirectory)\build\nuget /bl:$(build.artifactstagingdirectory)/win-bootstrap-devserver.binlog
      cp $(Build.SourcesDirectory)/build/CHANGELOG.md $(build.artifactstagingdirectory)
    displayName: Build packages

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)
      Contents: ' $(build.sourcesdirectory)\build\nuget\*.nupkg'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-wasm-bootstrap-drop
      ArtifactType: Container

  - script: |
      dotnet msbuild /r /bl /m:1 /p:Configuration=Release /p:DISABLE_CLIHOST_NET6=true /p:InformationalVersion=$(GITVERSION.INFORMATIONALVERSION) /p:PackageVersion=$(GITVERSION.FullSemVer) /p:PackageOutputPath=$(build.sourcesdirectory)\build\nuget $(build.sourcesdirectory)/src/Uno.Wasm.Bootstrap-msbuild-only.slnf /bl:$(build.artifactstagingdirectory)/win-validation-binaries.binlog

    displayName: Build Validation Binaries

  # - powershell: |
  #     cd $(build.sourcesdirectory)/src/Uno.Wasm.Node.Sample.Runner
  #     .\Validate.ps1
  #   displayName: Build Validation Binaries

  - task: VisualStudioTestPlatformInstaller@1

  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
        **\*UnitTests*.dll
        !**\ref\**
        !**\obj\**
      vstestLocationMethod: version
      vsTestVersion: latest
      testRunTitle: $(Agent.JobName)
      testSelector: testAssemblies

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-wasm-bootstrap-drop
      ArtifactType: Container

- template: .vsts-ci-linux.yml
  parameters:
    jobName: Linux_netcore3_1
    netcore_version: 3.1.201
    linux_container: unoplatform/wasm-build:3.0

- template: .vsts-ci-windows-tests.yml
  parameters:
    jobName: Windows_netcore3_1
    netcore_version: 3.1.201
    linux_container: unoplatform/wasm-build:3.0

- template: .vsts-ci-macos.yml
  parameters:
    jobName: macOS_netcore3_1
    vmImage: macOS-10.15
    netcore_version: 3.1.201