trigger:
  branches:
    include:
      - main
      - release/stable/*
      - feature/*

pr:
  branches:
    include:
      - main
      - release/stable/*
      - feature/*

variables:
  # disabled for now as the default has changed for net10
  NUGET_CERT_REVOCATION_MODE: offline

stages:
- stage: Determine_Changes
  displayName: Determine Changes
  jobs:
  - template: build/ci/stage-determine-changes.yml

- stage: Docs_Validations
  displayName: Docs Validations
  dependsOn: Determine_Changes
  # Trigger this stage when docs files are changed
  condition: or(eq(dependencies.Determine_Changes.outputs['evaluate_changes.DetermineChanges.docsOnly'], 'true'), eq(dependencies.Determine_Changes.outputs['evaluate_changes.DetermineChanges.mixedChanges'], 'true'))
  jobs:
  - template: build/ci/stage-docs-validations.yml

- stage: Packages
  displayName: Packages
  dependsOn: Determine_Changes
  # Don't trigger this stage if only docs files are changed
  condition: ne(dependencies.Determine_Changes.outputs['evaluate_changes.DetermineChanges.docsOnly'], 'true')
  jobs:
  - template: build/ci/stage-build-packages.yml
    parameters:
      jobName: Packages

- stage: Build_Tests
  displayName: Build Tests
  dependsOn: Determine_Changes
  # Don't trigger this stage if only docs files are changed
  condition: ne(dependencies.Determine_Changes.outputs['evaluate_changes.DetermineChanges.docsOnly'], 'true')
  jobs:
    - template: build/ci/stage-build-linux-tests.yml
      parameters:
        jobName: Linux_Tests
        linux_container: unoplatform/wasm-build:3.0
    - template: build/ci/stage-build-windows-tests.yml
      parameters:
        jobName: Windows_Tests
        linux_container: unoplatform/wasm-build:3.0
    - template: build/ci/stage-build-macos-tests.yml
      parameters:
        jobName: macOS_Tests
        vmImage: macOS-14
