parameters:
  jobName: ''
  netcore_version: ''

jobs:
- job: ${{ parameters.jobName }}

  pool:
    vmImage: 'windows-2019'

  workspace:
    clean: all
      
  variables:
    NUGET_PACKAGES: $(build.sourcesdirectory)/.nuget
    NETCORE_VERSION: ${{ parameters.netcore_version }}

  steps:
  - checkout: self
    clean: true

  - template: build/ci/gitversion.yml

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    condition: ne(variables['NETCORE_VERSION'], '2.2.x')
    inputs:
      packageType: sdk
      version: ${{ parameters.netcore_version }}
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: UseDotNet@2
    displayName: 'Install .NET 5 SDK'
    inputs:
      packageType: sdk
      version: '5.0.100'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - pwsh: |
      cd $(build.sourcesdirectory)/src/Uno.Wasm.Bootstrap
      dotnet msbuild /r /p:Configuration=Release /p:DISABLE_CLIHOST_NET6=true
    displayName: Build bootstrap

  - pwsh: |
      cd $(build.sourcesdirectory)/src
      dotnet msbuild /r /p:Configuration=Release /p:DISABLE_CLIHOST_NET6=true /t:Publish /m:1 Uno.Wasm.Bootstrap-netcore-only.slnf /bl:$(build.artifactstagingdirectory)/SampleNet5-win.binlog
    displayName: Build NetCore-Wasm Sample

  - pwsh: |
      $(build.sourcesdirectory)\build\scripts\run-tests-windows.ps1 `
      "$(build.sourcesdirectory)\src\Uno.Wasm.AotTests.net5\bin\Release\net5.0\dist" `
      "$(build.sourcesdirectory)\src\WasmAot.UITests" `
      "http://localhost:8000/"

    displayName: Raytracer UI Tests Net5
    env:
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"

  - pwsh: |
      $(build.sourcesdirectory)\build\scripts\run-tests-windows.ps1 `
      "$(build.sourcesdirectory)\src\Uno.Wasm.StaticLinking.Aot.Net5\bin\Release\net5.0\dist" `
      "$(build.sourcesdirectory)\src\Uno.Wasm.StaticLinking.Aot.UITests" `
      "http://localhost:8000/"

    displayName: StaticLinking.Aot Tests Net5
    env:
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-wasm-bootstrap-linux-aot
      ArtifactType: Container
