
jobs:
- template: .vsts-ci-packages.yml
  parameters:
    jobName: Packages

- template: .vsts-ci-linux.yml
  parameters:
    jobName: Linux_Tests
    linux_container: unoplatform/wasm-build:3.0

- template: .vsts-ci-windows-tests.yml
  parameters:
    jobName: Windows_Tests
    linux_container: unoplatform/wasm-build:3.0

- template: .vsts-ci-macos.yml
  parameters:
    jobName: macOS_Tests
    vmImage: macOS-15

- template: .vsts-ci-wsl-tests.yml
