jobs:
- job: Windows

  pool:
    vmImage: 'windows-2019'
    
  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget

  steps:
  - checkout: self
    clean: true

  - task: UseDotNet@2
    displayName: 'Install .NET 5 SDK'
    inputs:
      packageType: sdk
      version: '5.0.100'

  - task: UseDotNet@2
    displayName: 'Install .NET 3.1.403'
    inputs:
      packageType: sdk
      version: 3.1.403

  - template: build/ci/gitversion.yml
  - template: build/ci/dotnet-install.yml

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.9.1
      checkLatest: false

  - powershell: |
        $ErrorActionPreference = 'SilentlyContinue'
        cd $(build.sourcesdirectory)/src/WasmAot.UITests
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.StaticLinking.Aot.UITests
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.Node.Sample.Runner
        npm install
        cd $(build.sourcesdirectory)/src/Uno.Wasm.Threading.UITests
        npm install

    displayName: UI Tests npm dependencies

  - script: |
      cd $(build.sourcesdirectory)\src\Uno.Wasm.Bootstrap
      dotnet msbuild /r /p:Configuration=Release /p:InformationalVersion=$(GITVERSION.INFORMATIONALVERSION) /p:PackageVersion=$(GITVERSION.FullSemVer) /p:PackageOutputPath=$(build.sourcesdirectory)\build\nuget
      cd $(build.sourcesdirectory)\src\Uno.Wasm.Bootstrap.DevServer
      dotnet msbuild /r /p:Configuration=Release /p:InformationalVersion=$(GITVERSION.INFORMATIONALVERSION) /p:PackageVersion=$(GITVERSION.FullSemVer) /p:PackageOutputPath=$(build.sourcesdirectory)\build\nuget
    displayName: Build packages

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(build.sourcesdirectory)
      Contents: ' $(build.sourcesdirectory)\build\nuget\*.nupkg'
      TargetFolder: $(build.artifactstagingdirectory)
      CleanTargetFolder: false
      OverWrite: false
      flattenFolders: false

  - task: MSBuild@1
    inputs:
      solution: $(build.sourcesdirectory)/src/Uno.Wasm.Bootstrap-msbuild-only.slnf
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r /bl /p:Configuration=Release /p:InformationalVersion=$(GITVERSION.INFORMATIONALVERSION) /p:PackageVersion=$(GITVERSION.FullSemVer) /p:PackageOutputPath=$(build.sourcesdirectory)\build\nuget
      clean: false
      maximumCpuCount: false
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - powershell: |
        cd $(build.sourcesdirectory)/src/Uno.Wasm.Node.Sample.Runner
        .\Validate.ps1

  - task: VisualStudioTestPlatformInstaller@1

  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
        **\*UnitTests*.dll
        !**\ref\**
        !**\obj\**
      vstestLocationMethod: version
      vsTestVersion: latest
      testRunTitle: $(Agent.JobName)
      testSelector: testAssemblies

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uno-wasm-bootstrap-drop
      ArtifactType: Container

- template: .vsts-ci-linux.yml
  parameters:
    jobName: Linux_netcore3_1
    netcore_version: 3.1.201
    linux_container: unoplatform/wasm-build:3.0

- template: .vsts-ci-windows-tests.yml
  parameters:
    jobName: Windows_netcore3_1
    netcore_version: 3.1.201
    linux_container: unoplatform/wasm-build:3.0

- template: .vsts-ci-macos.yml
  parameters:
    jobName: macOS_netcore3_1
    vmImage: macOS-10.15
    netcore_version: 3.1.201